### ISSUE TITLE
Fix dependency on magick and pingo being .exes (For UNIX)

### ISSUE THREAD

**Issue by DrWhoCares** [DrWhoCares/imgdanke#8]
Currently hardcoded to look for magick.exe and pingo.exe. Remove that limitation when not on Windows.

**Comment by DrWhoCares** [comment]
Potentially fixed in fa7cbf24
Released in v1.2020.7.14
@Jaegrqualm Please verify the issue has been fixed.

**Comment by Jaegrqualm** [comment]
Ah, although this doesn't have much for WINE support, it does appear that this was a problem for mono support. support for mono still isn't complete, though, seeing as apparently some of the libraries used are not compatible, so it's currently unusable. That topic deserves its own issue, however.

**Comment by DrWhoCares** [comment]
Going to close this issue as fixed, feel free to open a new one for mono support specifically, or other individual items related to mono support requirements.
